force-app/main/default/objects/sfpegProfile__mdt/sfpegProfile__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to store a configuration of the sfpegProfiletCmp LWC component.
It contains the detailed layout of the component and actions to be displayed.</description>
    <label>sfpegProfile</label>
    <pluralLabel>sfpegProfiles</pluralLabel>
</CustomObject>

force-app/main/default/objects/sfpegProfile__mdt/fields/ProfileActions__c.field-meta.xml
<CustomField>
    <fullName>ProfileActions__c</fullName>
    <description>Configuration of the Actions displayed in the action bar between header and details (should be a sfpegAction record name)</description>
    <inlineHelpText>Configuration of the Actions displayed in the action bar between header and details  (should be a sfpegAction record name)</inlineHelpText>
    <label>Profile Actions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/extensions/sfpegProfile/objects/sfpegProfile__mdt/fields/ProfileAvatar__c.field-meta.xml
<CustomField>
    <fullName>ProfileAvatar__c</fullName>
    <description>Header avatar image of the profile component (image file path within the sfpegAvatar static resource)</description>
    <inlineHelpText>Header avatar image of the profile component (image file path within the sfpegAvatar static resource)</inlineHelpText>
    <label>Profile Avatar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegProfile__mdt/fields/ProfileBanner__c.field-meta.xml
<CustomField>
    <fullName>ProfileBanner__c</fullName>
    <description>Headline banner image of the profile component (image file path within the sfpegBanner static resource)</description>
    <inlineHelpText>Headline banner image of the profile component (image file path within the sfpegBanner static resource)</inlineHelpText>
    <label>Profile Banner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegProfile__mdt/fields/ProfileDetails__c.field-meta.xml
<CustomField>
    <fullName>ProfileDetails__c</fullName>
    <description>Configuration of the list of fields to be displayed in the Details section</description>
    <inlineHelpText>Configuration of the list of fields to be displayed in the Details section</inlineHelpText>
    <label>Profile Details</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sfpegProfile__mdt/fields/ProfileHeader__c.field-meta.xml
<CustomField>
    <fullName>ProfileHeader__c</fullName>
    <description>Configuration of the header content (background, avatar, badge, title and header details)</description>
    <inlineHelpText>Configuration of the header content (background, avatar, badge, title and header details)</inlineHelpText>
    <label>Profile Header</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/sfpegProfile_CTL.cls
/***
* @description  Lightning controller to provide details about existing Record Profile component configurations.
*               It relies on the sfpegProfile__mdt custom metadata.
* @author       P-E GROS
* @date         August 2021
* @see PEG_LIST package (https://github.com/pegros/PEG_LIST)
*
* Legal Notice
*
* MIT License
*
* Copyright (c) 2021 pegros
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
***/

@SuppressWarnings('PMD.ClassNamingConventions')
public with sharing class sfpegProfile_CTL {

    /***
    * @description  Simple method to fetch configuration details for a Record Profile component.
    *               It provides the display configuration as well as the actions available.
    * @param        name    DeveloperName of the Profile configuration record
    * @return       Object  sfpegProfile__mdt record with ProfileBanner__c, ProfileAvatar__c, ProfileHeader__c,
    *               ProfileActions__c, ProfileDetails__c, MasterLabel fields filled in.
    * @exception    AuraHandledException    Raised if no configuration found for the provided name
    ***/
    @AuraEnabled(cacheable=true)
    public static Object getConfiguration(final String name) {
        System.debug(LoggingLevel.FINE,'getConfiguration: START with sfpegProfile configuration name ' + name);

        List<sfpegProfile__mdt> configs = [ SELECT  MasterLabel, ProfileBanner__c, ProfileAvatar__c, ProfileHeader__c,
                                                    ProfileActions__c, ProfileDetails__c
                                            FROM sfpegProfile__mdt
                                            WHERE DeveloperName =  :name];

        if ((configs == null) || (configs.size() != 1)) {
            System.debug(LoggingLevel.ERROR,'getConfiguration: END KO / configuration not found with name ' + name);
            throw new AuraHandledException('Configuration not found with name ' + name);
        }

        //System.debug(LoggingLevel.FINEST,'getConfiguration: END with configuration name ' + configs[0]);
        System.debug(LoggingLevel.FINE,'getConfiguration: END ' + configs[0].MasterLabel);
        return (Object) (configs[0]);
    }

}