force-app/extensions/sfpegKpiList/objects/sfpegKpiList__mdt/sfpegKpiList__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to store a configuration of the sfpegKpiListCmp LWC component.
It contains the detailed layout of the KPIs and actions to be displayed.</description>
    <label>sfpegKpiList</label>
    <pluralLabel>sfpegKpiLists</pluralLabel>
</CustomObject>

force-app/main/default/objects/sfpegKpiList__mdt/fields/DisplayConfig__c.field-meta.xml
<CustomField>
    <fullName>DisplayConfig__c</fullName>
    <description>Display configuration (for sfpegKpiListCmp component)</description>
    <label>DisplayConfig</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/sfpegKpiList_CTL.cls
/***
* @description  Lightning controller to provide details about existing KPI List configurations.
*               It relies on the sfpegKpiList__mdt custom metadata.
* @author       P-E GROS
* @date         July 2021
*
* Legal Notice
* 
* MIT License
* 
* Copyright (c) 2021 pegros
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
***/

public with sharing class sfpegKpiList_CTL {
    
    /***
    * @description  Simple method to fetch configuration details for a KPI List component.
    *               It provides the display configuration as well as the actions available.
    * @param        name    DeveloperName of the KPI List configuration record
    * @return       Object  sfpegKpiList__mdt record with DisplayConfig__c, 
    *               MasterLabel fields filled in.
    * @exception    AuraHandledException    Raised if no configuration found for the provided name
    ***/
    @AuraEnabled(cacheable=true)
    public static Object getConfiguration(final String name) {
        System.debug(LoggingLevel.FINE,'getConfiguration: START with configuration name ' + name);

        List<sfpegKpiList__mdt> configs = [ SELECT MasterLabel, DisplayConfig__c
                                            FROM sfpegKpiList__mdt
                                            WHERE DeveloperName =  :name];
        if ((configs == null) || (configs.size() != 1)) {
            throw new AuraHandledException('Configuration not found with name ' + name);
        }
        //System.debug(LoggingLevel.FINEST,'getConfiguration: END with configuration name ' + configs[0]);
        System.debug(LoggingLevel.FINE,'getConfiguration: END ' + configs[0].MasterLabel);
        return (Object) (configs[0]);
    }

}