force-app/extensions/sfpegMessage/objects/sfpegMessage__mdt/sfpegMessage__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to store a configuration of the sfpegMessageListCmp LWC component.
It contains the configuration of all conditionally displayed messages to be displayed and their possible related actions.</description>
    <label>sfpegMessage</label>
    <pluralLabel>sfpegMessages</pluralLabel>
</CustomObject>

force-app/main/default/objects/sfpegMessage__mdt/fields/MessageActions__c.field-meta.xml
<CustomField>
    <fullName>MessageActions__c</fullName>
    <description>Configuration of the Actions used in the message actions (should be a sfpegAction record name)</description>
    <inlineHelpText>Configuration of the Actions used in the message actions (should be a sfpegAction record name)</inlineHelpText>
    <label>Message Actions</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/extensions/sfpegMessage/objects/sfpegMessage__mdt/fields/MessageDisplay__c.field-meta.xml
<CustomField>
    <fullName>MessageDisplay__c</fullName>
    <description>JSON Configuration of the different conditional messages to be displayed</description>
    <inlineHelpText>JSON Configuration of the different conditional messages to be displayed</inlineHelpText>
    <label>Message Display</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/sfpegMessage_CTL.cls
/***
* @description  Lightning controller to provide details about existing Message List configurations.
*               It relies on the sfpegMessage__mdt custom metadata.
* @author       P-E GROS
* @date         August 2021
* @see PEG_LIST package (https://github.com/pegros/PEG_LIST)
*
* Legal Notice
*
* MIT License
*
* Copyright (c) 2021 pegros
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
***/

@SuppressWarnings('PMD.ClassNamingConventions')
public with sharing class sfpegMessage_CTL {

    /***
    * @description  Simple method to fetch configuration details for a Message List component.
    *               It provides the display configuration as well as the actions available.
    * @param        name    DeveloperName of the Message configuration record
    * @return       Object  sfpegMessage__mdt record with MessageDisplay__c, MessageActions__c,
    *               MasterLabel fields filled in.
    * @exception    AuraHandledException    Raised if no configuration found for the provided name
    ***/
    @AuraEnabled(cacheable=true)
    public static Object getConfiguration(final String name) {
        System.debug(LoggingLevel.FINE,'getConfiguration: START with sfpegMessage configuration name ' + name);

        List<sfpegMessage__mdt> configs = [ SELECT MasterLabel, MessageDisplay__c, MessageActions__c
                                            FROM sfpegMessage__mdt
                                            WHERE DeveloperName =  :name];
        if ((configs == null) || (configs.size() != 1)) {
            throw new AuraHandledException('Configuration not found with name ' + name);
        }
        //System.debug(LoggingLevel.FINEST,'getConfiguration: END with configuration name ' + configs[0]);
        System.debug(LoggingLevel.FINE,'getConfiguration: END ' + configs[0].MasterLabel);
        return (Object) (configs[0]);
    }

}