force-app/main/default/objects/sfpegCardList__mdt/sfpegCardList__mdt.object-meta.xml
<CustomObject>
    <description>Configuration of the sfpegCardListCmp component, both in terms of records and layouts to be displayed in a list.</description>
    <label>sfpegCardList</label>
    <pluralLabel>sfpegCardLists</pluralLabel>
</CustomObject>

force-app/main/default/objects/sfpegCardList__mdt/fields/CardActions__c.field-meta.xml
<CustomField>
    <fullName>CardActions__c</fullName>
    <description>Name of the Action metadata record used for each card header actions.</description>
    <label>Card Actions</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/extensions/sfpegCard/objects/sfpegCardList__mdt/fields/CardActionsField__c.field-meta.xml
<CustomField>
    <fullName>CardActionsField__c</fullName>
    <description>API Name of the field providing the Action Header configuration name for each card in the query results.</description>
    <label>Card Actions Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegCardList__mdt/fields/CardConfig__c.field-meta.xml
<CustomField>
    <fullName>CardConfig__c</fullName>
    <description>Name of the sfpecCard metadata record to be used to display the records.</description>
    <label>Card Config</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegCardList__mdt/fields/CardConfigField__c.field-meta.xml
<CustomField>
    <fullName>CardConfigField__c</fullName>
    <description>Name of the field to be used to determine the card configuration to apply for each record (CardConfig value being applied by default)</description>
    <label>Card Config Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/extensions/sfpegCard/objects/sfpegCardList__mdt/fields/CardContext__c.field-meta.xml
<CustomField>
    <fullName>CardContext__c</fullName>
    <description>Context object to be provided as input to the Card level actions in the ROW token.</description>
    <label>Card Context</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/extensions/sfpegCard/objects/sfpegCardList__mdt/fields/IconName__c.field-meta.xml
<CustomField>
    <fullName>IconName__c</fullName>
    <description>Name of the icon (from SLDS) to be displayed on each record card header</description>
    <label>Icon Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegCardList__mdt/fields/IconNameField__c.field-meta.xml
<CustomField>
    <fullName>IconNameField__c</fullName>
    <description>API of the record field providing the Name of the icon (from SLDS) to be displayed on each record card header</description>
    <label>Icon Name Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegCardList__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Object API Name of the records being displayed in the cards.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegCardList__mdt/fields/ObjectNameField__c.field-meta.xml
<CustomField>
    <fullName>ObjectNameField__c</fullName>
    <description>Name of the field in the query results to be used to determine the Object Api Name of each record displayed in cards (Object Name being applied by default).</description>
    <label>Object Name Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/extensions/sfpegCard/objects/sfpegCardList__mdt/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>sfpegList metadata record used to fetch the IDs and Names of the records to be displayed in the sfpegCardListCmp component.</description>
    <label>Query</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegCardList__mdt/fields/RecordIdField__c.field-meta.xml
<CustomField>
    <fullName>RecordIdField__c</fullName>
    <defaultValue>&quot;Id&quot;</defaultValue>
    <description>Name of the query result field to be used to identify the records displayed in cards.</description>
    <label>Record ID Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sfpegCardList__mdt/fields/RecordNameField__c.field-meta.xml
<CustomField>
    <fullName>RecordNameField__c</fullName>
    <defaultValue>&quot;Name&quot;</defaultValue>
    <description>API Name of the field in the query result containing the Name of each record displayed in the card list.</description>
    <label>Record Name Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/sfpegCardList_CTL.cls
/***
* @description  Lightning controller to provide details about existing Card List configurations.
* @author       P-E GROS
* @date         Oct 2021
* @see PEG_LIST package (https://github.com/pegros/PEG_LIST)
*
* Legal Notice
*
* MIT License
*
* Copyright (c) 2021 pegros
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
***/

@SuppressWarnings('PMD.ClassNamingConventions')
public with sharing class sfpegCardList_CTL {

    /***
    * @description  Simple method to fetch configuration details for a Card List component.
    *               It provides the required displayed fields (and section).
    * @param        name                DeveloperName of the List configuration record
    * @return       Object              sfpegCardList__mdt record with Query__c, RecordIdField__c, RecordNameField__c,
    *                                   CardContext__c, IconName__c, IconNameField__c, ObjectName__c, ObjectNameField__c,
    *                                   CardConfig__c, CardConfigField__c, CardActions__c, CardActionsField__c
    *                                   and MasterLabel fields filled in.
    * @exception    AuraHandledException    Raised if no configuration found for the provided name
    ***/
    @AuraEnabled(cacheable=true)
    public static Object getConfiguration(final String name) {
        System.debug(LoggingLevel.FINE,'getConfiguration: START with sfpegCardList configuration name ' + name);

        List<sfpegCardList__mdt> configs = [    select  Query__c, RecordIdField__c, RecordNameField__c, CardContext__c,
                                                        IconName__c, IconNameField__c, ObjectName__c, ObjectNameField__c,
                                                        CardConfig__c, CardConfigField__c, CardActions__c, CardActionsField__c,  MasterLabel
                                                from sfpegCardList__mdt
                                                where DeveloperName =  :name    ];
        if ((configs == null) || (configs.size() != 1)) {
            System.debug(LoggingLevel.ERROR,'getConfiguration: END - Missing/wrong configuration ' + name);
            throw new AuraHandledException('Configuration not found with name ' + name);
        }
        //System.debug(LoggingLevel.FINEST,'getConfiguration: END with configuration name ' + configs[0]);
        System.debug(LoggingLevel.FINE,'getConfiguration: END ' + configs[0].MasterLabel);
        return (Object) (configs[0]);
    }
}